### ISSUE TITLE
Error: TypeError: Cannot read property 'status' of undefined when deploying to PoA

### ISSUE THREAD

**Issue by jcortejoso** [poanetwork/poa-bridge-contracts#182]
Hi!

I am trying to deploy the bridge contracts from `develop` branch (commit 1d61c2ca1b47837c3e073a472909ee2124c1a66e). 
This is the log output for deploying:

```Bridge mode: ERC_TO_ERC
deploying storage for home validators
pending txHash 0xa5fb92670eb0b9a5dbff10a997c6327b07a786d308f0a3076ae9a4a6d60993f8
[Home] BridgeValidators Storage:  0x7715a109b7AA85685cadCb1f668B61f3ccB6026b

deploying implementation for home validators
pending txHash 0xb6098717217da071c29bda4d5f5f5cc9b3884c5889d7ba93a104a9137bd27123
[Home] BridgeValidators Implementation:  0xba203333b1C0c30b09c03d70A22c85942A2c7db6

hooking up eternal storage to BridgeValidators
pending txHash 0x375ce9f2d1367a9862ee0558531a7100e35cd8d241874acbc7a4d29a9030b00b

initializing Home Bridge Validators with following parameters:

REQUIRED_NUMBER_OF_VALIDATORS: 1, VALIDATORS: 0xa1345ed0b2d1e193aead673e33dac56515af128a
pending txHash 0xffda957b418d0655d197f747537a8dfde40e6bd73bd4ddc39260234bfb8bb262
transferring proxy ownership to multisig for Validators Proxy contract
pending txHash 0x0e05c7ecb0e711d6da99c2c4217b010e99713ac806d6e6fcf41d7e2c5b7033c1

deploying homeBridge storage

pending txHash 0xe3fdde4814a617a6202c6b4c85a11eac75a7862394b5c0b6a1cbfd24d1017e54
[Home] HomeBridge Storage:  0xC8FeD1FF9e6435EDed54ca8Aa50bABd98c3a054f

deploying homeBridge implementation

pending txHash 0x63541e4de424e91ae4703ed2f4ed70e6274d8acbb7341f4ac23c60ccc8c4cb9b
[Home] HomeBridge Implementation:  0x4F11A14dCBf540D5a30cC8386D24c145342430F8

hooking up HomeBridge storage to HomeBridge implementation
pending txHash 0x7c0a4f007ff82b34fb59432b948f54a13d318d5ca7754e7f902ac561ce9599fd

[Home] deploying Bridgeble token
pending txHash 0xfb4c95c07740d3eabbd4711b4814ea27c6dfe18e1ba61cacbaaa87291d524e28
[Home] Bridgeble Token:  0x784a31D1faB2fb83A473228a2bA8A52085F58C78

set bridge contract on ERC677BridgeToken
pending txHash 0xb8633ecbf048093a8f5068b2e4cab2e143d8060202c0a3750e4eb30bd065d0ff
transferring ownership of Bridgeble token to homeBridge contract
pending txHash 0xf28d8733c48b8596daae6759f983dac9f93943f8f6b9cd7c563bff2a6b311bee

initializing Home Bridge with following parameters:

Home Validators: 0x7715a109b7AA85685cadCb1f668B61f3ccB6026b,
  HOME_DAILY_LIMIT : 30000000000000000000000000 which is 30000000 in eth,
  HOME_MAX_AMOUNT_PER_TX: 1500000000000000000000000 which is 1500000 in eth,
  HOME_MIN_AMOUNT_PER_TX: 500000000000000000 which is 0.5 in eth,
  HOME_GAS_PRICE: 1000000000, HOME_REQUIRED_BLOCK_CONFIRMATIONS : 1

pending txHash 0x9e1365e6d355d6fa4cffb0cba75dbac550664160ec8682de187516a3bbb63a87
transferring proxy ownership to multisig for Home bridge Proxy contract
pending txHash 0xabd1ec4278f3014b7162b8f37d23141fef7cfb99a7903e520f8a4ffdeedbabf7

Home Deployment Bridge completed

========================================
deploying ForeignBridge
========================================

deploying storage for foreign validators
pending txHash 0x05e10f5de84423b73b04cb11e884c208cf9c3398d952e47c8c951aaf79fb402a
[Foreign] BridgeValidators Storage:  0x0F631C3E3A402103dB1D7190B5112613258084cA

deploying implementation for foreign validators
pending txHash 0xf29270eabc07269ba702982fa4f41167726b76ff254be14883a179690b3f24cf
[Foreign] BridgeValidators Implementation:  0x70eEB389e0109aD6A76033B3C78e38fF16dF1A1B

hooking up eternal storage to BridgeValidators
pending txHash 0xcee9d58f49dd25d17ebf108a97d24eeb7414dc4d6affc597d1b11f73d92ce25a

initializing Foreign Bridge Validators with following parameters:

REQUIRED_NUMBER_OF_VALIDATORS: 1, VALIDATORS: 0xa1345ed0b2d1e193aead673e33dac56515af128a
pending txHash 0xc9f973cdea765212799366c7923532ff3f86dc9a8d21bd15d4cdca8112378e8d

Transferring ownership of ValidatorsProxy

pending txHash 0xea70b06c00556b6fb9597be610bcfa91c842240857a378e76bf7fa92fe7d94fd

deploying foreignBridge storage

pending txHash 0xb2df3260bddac5f08896d3541749333c0e03d3739f6c9f3be413f0d63eae8793
[Foreign] ForeignBridge Storage:  0x839307E1c21633e39deE601BeD5328C150799313

deploying foreignBridge implementation

pending txHash 0x25abfa8d13d096411af945ed380426e55822340eed51449f15050ef12446b406
[Foreign] ForeignBridge Implementation:  0xf7168C6c8BAbE53ea4365Fb774956a3fBA57b106

hooking up ForeignBridge storage to ForeignBridge implementation
pending txHash 0xc2c35f3788c5824843e1c3eb47ab72a69d62e68c14959fe453e8170db9c8be83

initializing Foreign Bridge with following parameters:

Foreign Validators: 0x0F631C3E3A402103dB1D7190B5112613258084cA,

Error: web3 RPC failed: {"code":-32016,"message":"The execution failed due to an exception."}
    at sendNodeRequest (/Users/jcortejoso/Projects/Ocean/poa-bridge-contracts/deploy/src/deploymentUtils.js:142:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: TypeError: Cannot read property 'status' of undefined
    at deployForeign (/Users/jcortejoso/Projects/Ocean/poa-bridge-contracts/deploy/src/erc_to_erc/foreign.js:201:63)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

The `.env` file is:
```
BRIDGE_MODE=ERC_TO_ERC
#BRIDGE_MODE=NATIVE_TO_ERC
DEPLOYMENT_ACCOUNT_PRIVATE_KEY=CD...
DEPLOYMENT_GAS_LIMIT_EXTRA=0.2
HOME_DEPLOYMENT_GAS_PRICE=10000000000
FOREIGN_DEPLOYMENT_GAS_PRICE=10000000000
GET_RECEIPT_INTERVAL_IN_MILLISECONDS=3000

BRIDGEABLE_TOKEN_NAME=OCEAN
BRIDGEABLE_TOKEN_SYMBOL=OCEAN
BRIDGEABLE_TOKEN_DECIMALS=18

HOME_RPC_URL=https://kovan.infura.io
HOME_BRIDGE_OWNER=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
HOME_VALIDATORS_OWNER=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
HOME_UPGRADEABLE_ADMIN=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
HOME_DAILY_LIMIT=30000000000000000000000000
HOME_MAX_AMOUNT_PER_TX=1500000000000000000000000
HOME_MIN_AMOUNT_PER_TX=500000000000000000
HOME_REQUIRED_BLOCK_CONFIRMATIONS=1
HOME_GAS_PRICE=1000000000

BLOCK_REWARD_ADDRESS=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2

FOREIGN_RPC_URL=https://nile.dev-ocean.com
FOREIGN_BRIDGE_OWNER=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
FOREIGN_VALIDATORS_OWNER=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
FOREIGN_UPGRADEABLE_ADMIN=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
FOREIGN_DAILY_LIMIT=15000000000000000000000000
FOREIGN_MAX_AMOUNT_PER_TX=750000000000000000000000
FOREIGN_MIN_AMOUNT_PER_TX=500000000000000000
FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS=8
FOREIGN_GAS_PRICE=10000000000
#for bridge erc_to_erc and erc_to_native mode
ERC20_TOKEN_ADDRESS=0xe90bf95f4a1ae6ce24ad89e6baefaa0137e15eaa
# Only for for erc_to_erc mode
ERC20_EXTENDED_BY_ERC677=false

REQUIRED_NUMBER_OF_VALIDATORS=1
#If several validators are used, list them separated by space without quotes
#E.g. VALIDATORS=0x 0x 0x
#VALIDATORS=0xa1345ed0b2d1e193aead673e33dac56515af128a 0xf4a2dbd5d67ef3019a7e4b188b92128c86d76bf9 0xcdbe5f61fac89e2cfcfa3727805d5cb8bc4f9afd
VALIDATORS=0xa1345ed0b2d1e193aead673e33dac56515af128a

#for bridge native_to_erc, erc_to_erc mode
DEPLOY_REWARDABLE_TOKEN=false
DPOS_STAKING_ADDRESS=0xDBA3b8287F7EE94A8638C19606D93f8cC11D3bb2
```

Transactions can be consulted in https://submarine.dev-ocean.com/. The PoA has the `eip658Transition` specification. If you need any additional data or need some token for testing in the PoA please ask me and will send.

Thank you!

Related with #62

**Comment by akolotov** [comment]
Is `0xe90bf95f4a1ae6ce24ad89e6baefaa0137e15eaa` a real contract? https://submarine.dev-ocean.com/address/0xe90bf95f4a1ae6ce24ad89e6baefaa0137e15eaa/transactions says "no".

**Comment by jcortejoso** [comment]
@akolotov thanks for the answer. Maybe I have not understood something perfectly. I thought that the ERC20 token address had to be deployed in the Home network (kovan in this case), https://blockscout.com/eth/kovan/address/0xe90bf95f4a1ae6ce24ad89e6baefaa0137e15eaa/transactions. I will try deploying that to Nile network.
