### ISSUE TITLE
erc20 to erc20 bridge error node deploy.js

### ISSUE THREAD

**Issue by dirmansebastian** [poanetwork/poa-bridge-contracts#63]
hey guys,

used that branch:https://github.com/poanetwork/poa-bridge-contracts/tree/erc20toErc20 

i got that error when i try to run node deploy.js
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../build/contracts/EternalStorageProxy.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/osboxes/Downloads/bridge/poa-bridge-contracts/deploy/src/home.js:11:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

i've deployed all my contracts manually on kovan and i've added ERC20_TOKEN_ADDRESS in env file:

```
BRIDGE_MODE=ERC_TO_ERC

DEPLOYMENT_ACCOUNT_ADDRESS=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
DEPLOYMENT_ACCOUNT_PRIVATE_KEY=f8482e4321ba51aeZZZZZZZZ1d708e8e45e200080020d554adc50
DEPLOYMENT_GAS_LIMIT=4000000
DEPLOYMENT_GAS_PRICE=10
GET_RECEIPT_INTERVAL_IN_MILLISECONDS=3000

HOME_RPC_URL=https://sokol.poa.network
HOME_OWNER_MULTISIG=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
HOME_UPGRADEABLE_ADMIN_VALIDATORS=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
HOME_UPGRADEABLE_ADMIN_BRIDGE=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
HOME_DAILY_LIMIT=30000000000000000000000000
HOME_MAX_AMOUNT_PER_TX=1500000000000000000000000
HOME_MIN_AMOUNT_PER_TX=500000000000000000
HOME_REQUIRED_BLOCK_CONFIRMATIONS=1
HOME_GAS_PRICE=1

FOREIGN_RPC_URL=https://sokol.poa.network
FOREIGN_OWNER_MULTISIG=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
FOREIGN_UPGRADEABLE_ADMIN_VALIDATORS=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
FOREIGN_UPGRADEABLE_ADMIN_BRIDGE=0x0D6CE14b31A5a5F7e3F206AE9a022D59ACAAaCFF
FOREIGN_DAILY_LIMIT=15000000000000000000000000
FOREIGN_MAX_AMOUNT_PER_TX=750000000000000000000000
FOREIGN_MIN_AMOUNT_PER_TX=500000000000000000
FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS=8
FOREIGN_GAS_PRICE=10
ERC20_TOKEN_ADDRESS=0x258Ec63D29A1ED1F603E0f6aa8a17B513E9c3bA7

REQUIRED_NUMBER_OF_VALIDATORS=1
VALIDATORS="0xE8DDc5c7A2d2F0D7a9798459c0104fDf5E987ACA 0x82e4e61e7f5139ff0a4157A5Bc687eF42294c248 0x23468dB7f4b8Ff4924B0709aB7Ae0971B3Bc8d28"
```

or is there any erc20 to erc20 branch stable?

thank you,
sebi

**Comment by akolotov** [comment]
hi @dirmansebastian!
`erc20toErc20` branch is not intended to be used. It is intermediate version of bridge contracts. If you want to use `ERC_TO_ERC` mode of the bridge please take a look at https://github.com/poanetwork/poa-bridge-contracts/tree/refactor_v1 branch. Actually this is a branch we plan to use in further development.

**Comment by dirmansebastian** [comment]
cool, i'll use https://github.com/poanetwork/poa-bridge-contracts/tree/refactor_v1 

thank you,
sebi
